name: uhdpromer
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libnsl=2.0.1
  - libsqlite=3.46.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.2
  - pip=24.2
  - python=3.9.20
  - readline=8.2
  - tk=8.6.13
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
    - absl-py==2.1.0
    - accelerate==1.0.0rc1
    - addict==2.4.0
    - asttokens==2.4.1
    - certifi==2024.8.30
    - charset-normalizer==3.3.2
    # - clip==1.0
    - colorama==0.4.6
    - contourpy==1.3.0
    - cycler==0.12.1
    - decorator==5.2.1
    - einops==0.8.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - facexlib==0.3.0
    - filelock==3.16.1
    - fonttools==4.54.1
    - fsspec==2024.9.0
    - ftfy==6.2.3
    - future==1.0.0
    - grpcio==1.66.2
    - huggingface-hub==0.25.1
    - icecream==2.1.3
    - idna==3.10
    - imageio==2.35.1
    - imgaug==0.4.0
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipython==8.18.1
    - jedi==0.19.2
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - lightning-utilities==0.11.7
    - llvmlite==0.43.0
    - lmdb==1.5.1
    - markdown==3.7
    - markupsafe==2.1.5
    - matplotlib==3.9.2
    - matplotlib-inline==0.1.7
    - networkx==3.2.1
    - numba==0.60.0
    - numpy==1.24.0
    - openai-clip==1.0.1
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
    - packaging==24.1
    - pandas==2.2.3
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==9.3.0
    - prompt-toolkit==3.0.51
    - protobuf==5.28.2
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pygments==2.18.0
    - pyiqa==0.1.12
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - pyyaml==6.0.2
    - regex==2024.9.11
    - requests==2.32.3
    - safetensors==0.4.5
    - scikit-image==0.24.0
    - scipy==1.13.1
    - sentencepiece==0.2.0
    - setuptools==75.1.0
    - shapely==2.0.6
    - six==1.16.0
    - stack-data==0.6.3
    # - tb-nightly==2.19.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tifffile==2024.8.30
    - timm==1.0.9
    - tokenizers==0.15.2
    #- torch==1.12.0 --index-url https://download.pytorch.org/whl/cu113/
    - torchaudio==0.12.0 --index-url https://download.pytorch.org/whl/cu113/
    - torchmetrics==1.4.2
    - torchvision==0.13.0 --index-url https://download.pytorch.org/whl/cu113/
    - tqdm==4.66.5
    - traitlets==5.14.3
    - transformers==4.37.2
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.3
    - wcwidth==0.2.13
    - werkzeug==3.0.4
    - yapf==0.40.2
    - zipp==3.20.2
